FORMAT: 1A
HOST: http://private-4358a-quickcoffee.apiary-mock.com

# quick-coffee

API заказа и оплаты кофе, напитков и других продуктов.

# Group  Клиентское API

## Места продажи [/supplier/place]

### Список [GET]

+ Request 

    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==


+ Response 200 (application/json; charset=utf-8)

        {
            "data": [{
                    "placeid": 4,
                    "address": "ул. Богдана Титомира 12",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300,
                    "supplier": {
                        "supplierid": 2,
                        "name": "Кафе Куриные потроха Ext",
                        "description": "Отборные куриные головы и лапки",
                        "sitelink": "http://kokoko.ru"
                    }
                },
                {
                    "placeid": 5,
                    "address": "ул. Богдана Титомира 11",
                    "latitude": 55.76844400,
                    "longitude": 37.65074300,
                    "supplier": {
                        "supplierid": 2,
                        "name": "Кафе Куриные потроха Ext",
                        "description": "Отборные куриные головы и лапки",
                        "sitelink": "http://kokoko.ru"
                    }
                }
            ]
        }


+ Response 500 (application/json; charset=utf-8)

        {
          "message": "Непредвиденная ошибка"
        }
        
## Близлежащие места проджи [/supplier/place?latitude={latitude}&longitude={longitude}&radius={radius}]
+ Parameters
    + latitude: `55.76844400` (number, required) - широта центра карты
    + longitude: `37.65074300` (number, required) - долгота центра карты
    + radius: `2000` (number, required) - радиус охвата в метрах
    

### Список [GET]

+ Request 

    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
            
+ Response 200 (application/json; charset=utf-8)

        {
          "data": [
            {
              "placeid": 4,
              "address": "ул. Богдана Титомира 12",
              "latitude": 55.76844400,
              "longitude": 37.65074300,
              "supplier": {
                "supplierid": 2,
                "name": "Кафе Куриные потроха Ext",
                "description": "Отборные куриные головы и лапки",
                "sitelink": "http://kokoko.ru"
              }
            },
            {
              "placeid": 5,
              "address": "ул. Богдана Титомира 11",
              "latitude": 55.76844400,
              "longitude": 37.65074300,
              "supplier": {
                "supplierid": 2,
                "name": "Кафе Куриные потроха Ext",
                "description": "Отборные куриные головы и лапки",
                "sitelink": "http://kokoko.ru"
              }
            }
          ]
        }

+ Response 500 (application/json; charset=utf-8)

        {
          "message": "Непредвиденная ошибка"
        }

## Меню заведения [/supplier/place/{id}/menu]
+ Parameters
    + id: 6 (number, required) - идентификатор заведения

### Список [GET]

+ Attributes
    + id: `3` (number, required) - идентификатор товара
    + name: `БигМак` (string, required) - наименование
    + description: `Всё на булочке с кунжутом` (string, required) - подробное описание
    + price: `2000` (number, required) - цена в копейках

+ Request 

    + Headers
        
            Authorization: Basic ZGVmYXVsdDp7QTY3QjkyRjQtMUJDRi00OThDLTgwMTctMTA4NTg0MkIzNjUwfQ==
    
+ Response 200 (application/json; charset=utf-8)

            {
              "data": [
                {
                  "id": 1,
                  "name": "БигМак",
                  "description": "Всё на булочке с кунжутом",
                  "price": 100
                },
                {
                  "id": 2,
                  "name": "Кофий",
                  "description": "Первосортный растворимый кофеёк",
                  "price": 100
                },
                {
                  "id": 3,
                  "name": "Шаурма",
                  "description": "Курица в лаваше",
                  "price": 151
                }
              ]
            }

+ Response 500 (application/json; charset=utf-8)

        {
          "message": "Непредвиденная ошибка"
        }

+ Response 404 (application/json; charset=utf-8)

        {
          "message": "Данной точки не существует"
        }

## Проверка авторизации [/customer/auth]

### Список [GET]

+ Response 200 (application/json; charset=utf-8)

+ Response 500 (application/json; charset=utf-8)

        {
          "message": "Непредвиденная ошибка"
        }

## Регистрация [/customer/register]        

### Заказ [POST]

+ Request (application/json; charset=utf-8)

        {
          "customerInfo": {
            "surname": "Немытый",
            "name": "Альфонс",
            "patronymic": "Даздранагонович",
            "phone": "+75551112233",
            "email": "test@iddqd.ru"
          },
          "basicAuth": {
            "login": "onotole",
            "pass": "1"
          }
        }

+ Response 200 (application/json; charset=utf-8)

+ Response 409 (application/json; charset=utf-8)
        
        {
            "message": "Такой логин уже используется"
        } 


## Оформить заказ [/supplier/place/{id}/order]

+ Parameters
    + id: `1` (number, required) - идентификатор заведения


### Заказ [POST]

+ Request (application/json; charset=utf-8)

        {
          "dateServe": "2016-02-15T01:20:59.1395229+06:00",
          "items": [
            {
              "id": 1,
              "quantity": 1
            },
            {
              "id": 2,
              "quantity": 2
            }
          ]
        }

+ Response 201 (application/json; charset=utf-8)

    + Headers

            Location: /supplier/places/{id}/order/1


    + Body

            {
              "data": {
                "orderId": 10,
                "total": 300,
                "auth": {
                  "login": "10",
                  "pass": "0371bb99"
                }
            }


## Оплата заказа по криптопрограмме [/supplier/order/{id}]        
+ Parameters
    + id: `1` (number, required) - идентификатор заказа  

### Оплата [POST]

+ Request (application/json; charset=utf-8)

            {
              "recurring": false,
              "saveCard": false,
              "cryptogram": "024242424242161204KQcvRR4nXXKAH+OvXuxwyDjjeep6Tb05d+8LtUs8nQIKdhZrh5f25jhNgpG0eu0sa0XqQ6NING\\/B597UBD2xTlvxjEGe4oFdId9d5H0NsquoMs1rHquz7FoRSO6Mzwffvmo\\/HVRWAmZfJj9CpMS98vnwdAAMv02nk+ytUnVf\\/zJ0MBmcGiotmgddwhJBSC8avBdBtQU+cd8ecEoCjWs\\/ycYI2rwm5Zw1UZajutH6BemF0ALpdLD97jIOuGL1XLcyQva5dCwuki1eMGkXbs6I0fCt2lL\\/PlXvkN2TepmAGGhDmP2n7HMP8CEG4WN4kfShNNslj\\/L\\/EZZe4je9JwDy6g==",
              "IpAddress": "127.0.0.1",
              "cardOwnerName": "sdfsfds"
            }

+ Response 201 (application/json; charset=utf-8)